### ISSUE TITLE
1.5.0 fails to build (error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'nodes')

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/osm2pgsql#1517]
The Debian package build for osm2pgsql fails since the updated to 1.5.0:
```
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::node_set(const osmium::Node&)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:321:37: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'nodes'
  321 |         m_db_copy.new_line(m_tables.nodes().copy_target());
      |                                     ^~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::node_delete(osmid_t)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:362:37: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'nodes'
  362 |         m_db_copy.new_line(m_tables.nodes().copy_target());
      |                                     ^~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::way_set(const osmium::Way&)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:384:33: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'ways'
  384 |     m_db_copy.new_line(m_tables.ways().copy_target());
      |                                 ^~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::way_delete(osmid_t)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:483:33: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'ways'
  483 |     m_db_copy.new_line(m_tables.ways().copy_target());
      |                                 ^~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::relation_set(const osmium::Relation&)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:496:33: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'relations'
  496 |     m_db_copy.new_line(m_tables.relations().copy_target());
      |                                 ^~~~~~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'void middle_pgsql_t::relation_delete(osmid_t)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:559:33: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'relations'
  559 |     m_db_copy.new_line(m_tables.relations().copy_target());
      |                                 ^~~~~~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'virtual void middle_pgsql_t::after_nodes()':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:567:38: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'nodes'
  567 |         auto const &table = m_tables.nodes();
      |                                      ^~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'virtual void middle_pgsql_t::after_ways()':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:575:34: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'ways'
  575 |     auto const &table = m_tables.ways();
      |                                  ^~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In member function 'virtual void middle_pgsql_t::after_relations()':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:582:34: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'relations'
  582 |     auto const &table = m_tables.relations();
      |                                  ^~~~~~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp: In constructor 'middle_pgsql_t::middle_pgsql_t(std::shared_ptr<thread_pool_t>, const options_t*)':
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:808:14: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'nodes'
  808 |     m_tables.nodes() =
      |              ^~~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:810:14: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'ways'
  810 |     m_tables.ways() =
      |              ^~~~
/build/osm2pgsql-1.5.0+ds/src/middle-pgsql.cpp:813:14: error: 'class osmium::nwr_array<middle_pgsql_t::table_desc>' has no member named 'relations'
  813 |     m_tables.relations() = table_desc{*options, sql_for_relations()};
      |              ^~~~~~~~~
```
It doesn't appear related to rapidjson, the error occurs with and without external rapidjson.

**Comment by sebastic** [comment]
It seems osm2pgsql now requires libosmium 2.17.0, building the osm2pgsql Debian package with that instead of 2.16.0 resolves the issue.

Documenting this minimum version requirement when building with the external versions is probably a good thing.

**Comment by pnorman** [comment]
If I'm reading https://github.com/openstreetmap/osm2pgsql/blob/52b68715ed06d84a381d638df208d596173482e5/CMakeLists.txt#L193 our stated minimum is 2.15.6, which is probably wrong.
