### PR TITLE
Optionally enable C++11

### PR DESCRIPTION
**Pull request by lonvia**
Second attempt to enable C++11. This could do with some testing with different compilers. I've already run into bugs with boost 1.49 (as used in Debian stable).

@pnorman could you test again with your clang setup? Please make sure to run `make distclean` before compiling.

### CODE REVIEW

**Comment by pnorman** [comment]
```
[pnorman@pippin /usr/home/pnorman/osm/osm2pgsql]$ gmake
gmake  all-am
gmake[1]: Entering directory '/usr/home/pnorman/osm/osm2pgsql'
depbase=`echo osmdata.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H -I.  -D_THREAD_SAFE -pthread -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/include
-I/usr/include -I/usr/local/include -I/usr/local/include -DOSM2PGSQL_DATADIR='"/usr/local/share/osm2pgsql"' -Igeos-fallback -I/usr/local/include/lua52 -I/usr/lo
cal/include   -g -O2 -Wall -std=gnu++11 -MT osmdata.lo -MD -MP -MF $depbase.Tpo -c -o osmdata.lo osmdata.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -D_THREAD_SAFE -pthread -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/include -I/usr/include -I/usr/local/
include -I/usr/local/include -DOSM2PGSQL_DATADIR=\"/usr/local/share/osm2pgsql\" -Igeos-fallback -I/usr/local/include/lua52 -I/usr/local/include -g -O2 -Wall -st
d=gnu++11 -MT osmdata.lo -MD -MP -MF .deps/osmdata.Tpo -c osmdata.cpp  -fPIC -DPIC -o .libs/osmdata.o
In file included from osmdata.cpp:1:
In file included from ./osmdata.hpp:8:
In file included from /usr/local/include/boost/shared_ptr.hpp:17:
In file included from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:27:
In file included from /usr/local/include/boost/config/no_tr1/memory.hpp:21:
In file included from /usr/include/c++/v1/memory:603:
/usr/include/c++/v1/tuple:320:11: error: rvalue reference to type 'boost::thread_detail::default_barrier_reseter' cannot bind to lvalue of type
      'boost::thread_detail::default_barrier_reseter'
        : value(__t.get())
          ^     ~~~~~~~~~
/usr/include/c++/v1/tuple:444:8: note: in instantiation of member function 'std::__1::__tuple_leaf<0, boost::thread_detail::default_barrier_reseter &&,
      false>::__tuple_leaf' requested here
struct __tuple_impl<__tuple_indices<_Indx...>, _Tp...>
       ^
/usr/include/c++/v1/functional:1286:26: note: in instantiation of member function 'std::__1::__function::__func<boost::thread_detail::default_barrier_reseter,
      std::__1::allocator<boost::thread_detail::default_barrier_reseter>, unsigned long ()>::__func' requested here
            ::new (__f_) _FF(_VSTD::move(__f));
                         ^
/usr/local/include/boost/thread/barrier.hpp:108:55: note: in instantiation of function template specialization 'std::__1::function<unsigned long
      ()>::function<boost::thread_detail::default_barrier_reseter>' requested here
      m_count(check_counter(count)), m_generation(0), fct_(thread_detail::default_barrier_reseter(count))

...
```

**Comment by lonvia** [comment]
Looks like a bug specific to the libc++ version in FreeBSD: https://groups.google.com/forum/#!topic/fa.freebsd.current/iKNLKbRgFZw

**Comment by pnorman** [comment]
ugh.

I'd probably be able (and reluctantly willing) to patch around this on my machine, but others wouldn't, and I expect it would break the osm2pgsql port. Do we know if this also impacts OS X?

Options that I see include

* Not enabling C++11
* Enabling it when available, but detect the error with the code in [llvm bug 17798](https://llvm.org/bugs/show_bug.cgi?id=17798) and if present don't enable
* Enable it when available and break compilation on systems with the libc++ bug

cc @AMDmi3

**Comment by AMDmi3** [comment]
Which system do you get this error on? In FreeBSD that problem was fixed ~ a year ago and the only release is affected (FreeBSD 10.0) had already reached its end of life, so neither supported FreeBSD release has this problem. I've confirmed that it builds fine on 10.1, other versions will build by tomorrow. I'd vote for

> Enable it when available and break compilation on systems with the libc++ bug

**Comment by pnorman** [comment]
> Which system do you get this error on? In FreeBSD that problem was fixed ~ a year ago and the only release is affected (FreeBSD 10.0) had already reached its end of life, so neither supported FreeBSD release has this problem. I've confirmed that it builds fine on 10.1

uname reports FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 19:00:21 UTC 2015

**Comment by AMDmi3** [comment]
Strange, it builds fine in poudriere on 8.4, 9.3, 10.1 and recent -current. It doesn't link on i386 though:

```
./.libs/libosm2pgsql.a(osmdata.o): In function `boost::lockfree::queue<pending_job_t, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::~queue()':
osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev]+0x54): undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev]+0x72): undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev]+0x9b): undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_ED2Ev]+0xb9): undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
./.libs/libosm2pgsql.a(osmdata.o): In function `bool boost::lockfree::queue<pending_job_t, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::pop<pending_job_t>(pending_job_t&)':
osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_E3popIS2_EEbRT_[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_E3popIS2_EEbRT_]+0x44): undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
./.libs/libosm2pgsql.a(osmdata.o):osmdata.cpp:(.text._ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_E3popIS2_EEbRT_[_ZN5boost8lockfree5queueI13pending_job_tNS_9parameter5void_ES4_S4_E3popIS2_EEbRT_]+0x74): more undefined references to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)' follow
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```
but that seems unrelated and probably should be fixed by linking to libboost_atomic.

**Comment by pnorman** [comment]
I reduced the problem to an issue on my end with versions. I'd still like to check for the bug with configure as there's probably OS X versions with the same bug present.

**Comment by lonvia** [comment]
I'm with @AMDmi3 here to simply let the libc++ version break because sooner or later C++11 will become mandatory (hopefully sooner) and then testing won't help much either.

Could somebody confirm that this branch builds ok on a recent Mac OS X, @systemed maybe?

**Comment by lonvia** [comment]
@AMDmi3 The link error looks like a general 32bit building issue. I don't think anybody has tried to build with 32bit recently. I'll have a look at it.

**Comment by pnorman** [comment]
> but that seems unrelated and probably should be fixed by linking to libboost_atomic

Is that a new bug or an existing i386 one?

**Comment by pnorman** [comment]
> I'm with @AMDmi3 here to simply let the libc++ version break because sooner or later C++11 will become mandatory (hopefully sooner) and then testing won't help much either.

Ya, I could see that. But let's tag a new release first.

**Comment by AMDmi3** [comment]
> Is that a new bug or an existing i386 one?

Not sure. Before it didn't build without --without-lockfree at all, then it was fixed (#196 probably), I've successfully built it to confirm, however that is likely that I've only tried amd64.

**Comment by systemed** [comment]
Sorry - have tried to test this on OS X, but I'm still running into #144.

**Comment by lonvia** [comment]
The linking issue has already been reported in #231, commenting there.

**Comment by lonvia** [comment]
Is it ok to merge this, now that the release has been tagged? It's a prerequisite for fixing #231.

**Comment by pnorman** [comment]
I'd like to know if the llvm bug impacts OS X versions. If so, we need to detect it

**Comment by pnorman** [comment]
wfm on my OS X laptop
